### ISSUE TITLE
Receiver class io.jaegertracing.internal.JaegerTracer does not define or inherit an implementation of the resolved method abstract activateSpan

### ISSUE THREAD

**Issue by apemost** [opentracing-contrib/java-kafka-client#43]
Version: 0.1.0

```
java.lang.AbstractMethodError: Receiver class io.jaegertracing.internal.JaegerTracer does not define or inherit an implementation of the resolved method abstract activateSpan(Lio/opentracing/Span;)Lio/opentracing/Scope; of interface io.opentracing.Tracer.

  at io.opentracing.util.GlobalTracer.activateSpan(GlobalTracer.java:214)
  at io.opentracing.contrib.kafka.TracingKafkaProducer.send(TracingKafkaProducer.java:117)
  at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:372)
  at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:184)
  at com.gllue.gafka.GafkaConsumerProviderTest.kafkaTest(GafkaConsumerProviderTest.kt:21)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
  at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by malafeev** [comment]
Version `0.1.0` is based on opentracing api `0.32.0`.
But Jaeger doesn't support `0.32.0` yet.
Please use version `0.0.20` https://mvnrepository.com/artifact/io.opentracing.contrib/opentracing-kafka-client/0.0.20

**Comment by apemost** [comment]
@malafeev Thanks!
